import React, { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'

import Facebook from '../images/icon-facebook.svg'
import Twitter from '../images/icon-twitter.svg'
import Instagram from '../images/icon-instagram.svg'
import Youtube from '../images/icon-youtube.svg'


export default function Home() {

  const [darkmode, setDarkMode] = useState(true)

  function toggleTheme() {
    if (darkmode) {
      setDarkMode(false);
    } else {
      setDarkMode(true);
    }
  }

  return (
    <div className={darkmode ? "container-dark" : "container"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={darkmode ? "hero-dark" : "hero"}>
        <div className="row">
          <div className={darkmode ? "hero-col-dark" : "hero-col"}>
            <h1>Social Media Dashboard</h1>
            <p>Total Followers: 23,004</p>
          </div>
          <div className={darkmode ? "hero-col-dark toogle" : "hero-col toogle"}>
            <h3>Dark Mode</h3>
            <label className="switch">
              <input type="checkbox" id="switch" onClick={() => toggleTheme()} />
              <span className="slider round"></span>
            </label>
          </div>
        </div>

      </section>


      <section className="follower">
        <div className="row">
          <div className={darkmode ? "follower-card-dark" : "follower-card"}>
            <div className="facebook"></div>
            <div className="follower-content">
              <div className={darkmode ? "tag-dark" : "tag"}>
                <Image src={Facebook} alt="Facebook" />
                <p>@nathanf</p>
              </div>
              <h1 className={darkmode ? "count-dark" : "count"}>1987</h1>
              <p className={darkmode ? "subtext-dark" : "subtext"}>Followers</p>
              <p className="newfollower"><i className="fas fa-caret-up"></i>12 Today</p>

            </div>

          </div>

          <div className={darkmode ? "follower-card-dark" : "follower-card"}>
            <div className="twitter"></div>
            <div className="follower-content">
              <div className={darkmode ? "tag-dark" : "tag"}>
                <Image src={Twitter} alt="Twitter" />
                <p>@nathanf</p>
              </div>
              <h1 className={darkmode ? "count-dark" : "count"}>1044</h1>
              <p className={darkmode ? "subtext-dark" : "subtext"}>Followers</p>
              <p className="newfollower"><i className="fas fa-caret-up"></i>99 Today</p>
            </div>

          </div>

          <div className={darkmode ? "follower-card-dark" : "follower-card"}>
            <div className="instagram"></div>
            <div className="follower-content">
              <div className={darkmode ? "tag-dark" : "tag"}>
                <Image src={Instagram} alt="Instagram" />
                <p>@realnathanf</p>
              </div>
              <h1 className={darkmode ? "count-dark" : "count"}>11k</h1>
              <p className={darkmode ? "subtext-dark" : "subtext"}>Followers</p>
              <p className="newfollower"><i className="fas fa-caret-up"></i>1099 Today</p>
            </div>

          </div>

          <div className={darkmode ? "follower-card-dark" : "follower-card"}>
            <div className="youtube"></div>
            <div className="follower-content">
              <div className={darkmode ? "tag-dark" : "tag"}>
                <Image src={Youtube} alt="Youtube" />
                <p>Nathan F.</p>
              </div>
              <h1 className={darkmode ? "count-dark" : "count"}>8239</h1>
              <p className={darkmode ? "subtext-dark" : "subtext"}>Subscribers</p>
              <p className="losefollower"><i className="fas fa-caret-down"></i>144 Today</p>
            </div>

          </div>
        </div>
      </section>

      <section className={darkmode ? "overview-dark" : "overview"}>
        <div className="row">
          <h2>Overview - Today</h2>
        </div>
        <div className="row">
          <div className={darkmode ? "overview-card-dark" : "overview-card"}>
            <div className={darkmode ? "overview-header-dark" : "overview-header"}>
              <p>Page Views</p>
              <Image src={Facebook} alt="Facebook" />
            </div>
            <div className={darkmode ? "overview-content-dark" : "overview-content"}>
              <h3>87</h3>
              <p className="newfollower"><i className="fas fa-caret-up"></i>3%</p>
            </div>
          </div>

          <div className={darkmode ? "overview-card-dark" : "overview-card"}>
            <div className={darkmode ? "overview-header-dark" : "overview-header"}>
              <p>Likes</p>
              <Image src={Facebook} alt="Facebook" />
            </div>
            <div className={darkmode ? "overview-content-dark" : "overview-content"}>
              <h3>52</h3>
              <p className="losefollower"><i className="fas fa-caret-down"></i>2%</p>
            </div>
          </div>

          <div className={darkmode ? "overview-card-dark" : "overview-card"}>
            <div className={darkmode ? "overview-header-dark" : "overview-header"}>
              <p>Likes</p>
              <Image src={Instagram} alt="Instagram" />
            </div>
            <div className={darkmode ? "overview-content-dark" : "overview-content"}>
              <h3>5462</h3>
              <p className="newfollower"><i className="fas fa-caret-up"></i>2257%</p>
            </div>
          </div>

          <div className={darkmode ? "overview-card-dark" : "overview-card"}>
            <div className={darkmode ? "overview-header-dark" : "overview-header"}>
              <p>Profile Views</p>
              <Image src={Instagram} alt="Instagram" />
            </div>
            <div className={darkmode ? "overview-content-dark" : "overview-content"}>
              <h3>52k</h3>
              <p className="newfollower"><i className="fas fa-caret-up"></i>1375%</p>
            </div>
          </div>

        </div>

        <div className="row">

          <div className={darkmode ? "overview-card-dark" : "overview-card"}>
            <div className={darkmode ? "overview-header-dark" : "overview-header"}>
              <p>Retweets</p>
              <Image src={Twitter} alt="Twitter" />
            </div>
            <div className={darkmode ? "overview-content-dark" : "overview-content"}>
              <h3>117</h3>
              <p className="newfollower"><i className="fas fa-caret-up"></i>303%</p>
            </div>
          </div>

          <div className={darkmode ? "overview-card-dark" : "overview-card"}>
            <div className={darkmode ? "overview-header-dark" : "overview-header"}>
              <p>Likes</p>
              <Image src={Twitter} alt="Twitter" />
            </div>
            <div className={darkmode ? "overview-content-dark" : "overview-content"}>
              <h3>507</h3>
              <p className="newfollower"><i className="fas fa-caret-up"></i>553%</p>
            </div>
          </div>

          <div className={darkmode ? "overview-card-dark" : "overview-card"}>
            <div className={darkmode ? "overview-header-dark" : "overview-header"}>
              <p>Likes</p>
              <Image src={Youtube} alt="Youtube" />
            </div>
            <div className={darkmode ? "overview-content-dark" : "overview-content"}>
              <h3>107</h3>
              <p className="losefollower"><i className="fas fa-caret-down"></i>19%</p>
            </div>
          </div>

          <div className={darkmode ? "overview-card-dark" : "overview-card"}>
            <div className={darkmode ? "overview-header-dark" : "overview-header"}>
              <p>Page Views</p>
              <Image src={Youtube} alt="Youtube" />
            </div>
            <div className={darkmode ? "overview-content-dark" : "overview-content"}>
              <h3>1407</h3>
              <p className="losefollower"><i className="fas fa-caret-down"></i>12%</p>
            </div>
          </div>

        </div>

      </section>

      <div className="attribution">
        Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>. Coded by <a href="#">Elie Munsi</a>.
      </div>
    </div>
  )
}
